### ISSUE TITLE
doesn't work with e22 anymore

### ISSUE THREAD

**Issue by hupfdule** [mbert/etheme-blingbling-e20#13]
Unfortunately this theme doesn't work with e22 anymore. If trying to load it it falls back to the default theme.

Would be great if you could adapt it too work with e22 too (I can't image why the e developers keep modifying the theme engine so that old themes break again and again).

**Comment by mbert** [comment]
Which build did you use? I ust tried with release 0.9.2 (the latest), and it works just fine. I am using the latest 0.22 release of enlightenment. Maybe something else is the problem?

**Comment by hupfdule** [comment]
I also tried 0.9.2 and as this didn't work I pulled the repository and built it myself. The effect was the same.
I used the e22 release that is included in Debian buster now, which is 0.22.3.
Other themes are working, so there must be some problem with this theme.

**Comment by mbert** [comment]
I am using 0.22.3, too. Have you tried out the other theme from my github repo, Vulcan Retro? 
Also, which version of the efl library do you run? On my box it is 1.20.7.

**Comment by hupfdule** [comment]
Sorry for my late reply.

It is a strange thing. I now tried Vulcan Retro as well as some other themes from www.enlightenment-themes.org. None of them works. However, I have here an old skin laying around, called "ice", which is working. I looked into the code and it says it is using theme api version 1.10. Do you know what this means?

[ice.edj.zip](https://github.com/mbert/etheme-blingbling-e20/files/2175348/ice.edj.zip)

I also looked into the dependencies of the debian package for e22. It depends on those packages:

    libasound2 (>= 1.0.16), libbluetooth3 (>= 4.91), libc6 (>= 2.15),                                                                                                 
    libecore-con1 (>= 1.20.7-0~eo), libecore-evas1 (>= 1.20.7-0~eo),
    libecore-file1 (>= 1.20.7-0~eo), libecore-input1 (>= 1.20.7-0~eo),
    libecore-ipc1 (>= 1.20.7-0~eo), libecore-x1 (>= 1.20.7-0~eo), libecore1 (>= 
    1.20.7-0~eo), libedje1 (>= 1.20.7-0~eo), libeet1 (>= 1.20.7-0~eo), libeeze1
    (>= 1.20.7-0~eo), libefreet-bin, libefreet1a (>= 1.20.7-0~eo), libeina1a
    (>= 1.20.7-0~eo), libeio1 (>= 1.20.7-0~eo), libelementary1 (>= 
    1.20.7-0~eo), libemile1 (>= 1.20.7-0~eo), libemotion1 (>= 1.20.7-0~eo),
    libevas1 (>= 1.20.7-0~eo), libpam0g (>= 0.99.7.1), libpulse0 (>= 0.99.1),
    libxcb-keysyms1 (>= 0.4.0), libxcb-shape0, libxcb1,
    default-dbus-session-bus | dbus-session-bus, enlightenment-data (=
    0.22.3-2), libedje-bin, libevas1-engines-x

It seems that the debian package does not depend on the efl as a whole, but instead of the single sublibraries of the efl. However they seem to have the same version as yours: 1.20.7.

Are the debian packages broken? Or is there some strange dependency on a very old lib?

**Comment by mbert** [comment]
Your dependencies look fine to me. efl is not a single library but a collection of libraries. If the Debian folks prefer to model their pacakges' dependencies that way, this is perfectly OK. The efl libraries' versions are also up-to-date.

Theme API version is used for checking whether a theme's features work with an enlightenment version. 

I am far from being an expert. "My" two themes are the first and only I have created, mostly by "stealing" from other people's code. 

Since you seem to be the only person having this problem I'm afraid it looks like the reason must be somewhere beyond the themes and rather in your setup. I used to get a lot of help in the Bodhi Linux forum which was recently closed due to GDPR. They seem to have moved to https://www.linuxquestions.org/questions/bodhi-92/ and https://www.reddit.com/r/bodhilinux/

**Comment by hupfdule** [comment]
I have set up a new virtual machine with Debian Buster. It is working correctly there. I don't know the reason why it doesn't on my other installation.
Neverthelesse it seems not to be caused by the theme.
I therefore close this issue again.
Thanks for your help!
